# Generated by Django 2.1.8 on 2019-04-12 16:21
from django.core.management import call_command
from django.db import migrations, models


def reorder_filters(apps, schema_editor):
    call_command('reorder', 'advanced_filters.AdvancedFilter')


class Migration(migrations.Migration):

    dependencies = [
        ('advanced_filters', '0004_advancedfilter_model_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advancedfilter',
            options={'ordering': ('order',), 'verbose_name': 'Advanced Filter', 'verbose_name_plural': 'Advanced Filters'},
        ),
        migrations.AddField(
            model_name='advancedfilter',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(reorder_filters, migrations.RunPython.noop)
    ]
