# Generated by Django 2.1.8 on 2019-04-14 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advanced_filters', '0005_auto_20190412_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancedfilter',
            name='heading',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
